### ISSUE TITLE
[BUG] Update Station should not state 'No update available. …' when there is no connection to the Internet

### ISSUE THREAD

**Issue by grahamperrin** [ghostbsd/update-station#20]
### Steps

1. Be temporarily (unknowingly) without a connection to the Internet
2. open Update Station

### Expected

3. Update Station should state that it cannot check for updates

### Actual behaviour

3. Update Station states: 

> No update available. This computer is up-to-date.

![image](https://user-images.githubusercontent.com/192271/117092509-592f5900-ad56-11eb-924f-df02b560d38b.png)

**Comment by ericbsd** [comment]
@vimanuelt I did something similar with Software Station if you need an example.

**Comment by ericbsd** [comment]
Here is what I have done.
![image](https://user-images.githubusercontent.com/4249848/150518495-02a170a6-d6cd-454d-befa-1bc39f7e050a.png)
