### ISSUE TITLE
Only one update-station process should be allowed to run

### ISSUE THREAD

**Issue by danboid** [ghostbsd/update-station#27]
I installed ghostbsd for the first time tonight and overall I'm very impressed. I always thought one of FreeBSDs weakest points was its installer and you've done a great job of fixing that and I like lots of the other tweaks over vanilla FreeBSD such as including pulseaudio by default. I'm a big fan of ZFS so it was very nice to see a few different ZFS options available.

One of the first things I did after installation was to run Update Station. It got half way through installing several hundred updates and then it popped open another "You have updates ready to be installed" window, just like the one I had clicked "Install updates" on only a few minutes earlier. I wasn't thinking and clicked on the second "Install updates" which pretty quickly caused both update processes to fail, unsurprisingly.

**Comment by ericbsd** [comment]
Completed!  It will be available in an update soon.

**Comment by danboid** [comment]
Thanks Eric!

There's one thing stopping me switching from Linux to GhostBSD and that is hot swapping USB audio doesn't work. I have got my main USB sound card to work under GhostBSD but if I unplug it it doesn't work when I plug it back in without rebooting.

I have yet to test the latest FreeBSD (14?) code to see if this is still an issue and thats where it needs to be fixed but I just thought you should know. Otherwise I think GhostBSD is better than Ubuntu or Arc for me but I use the hell out of my soundcards so this is a showstopper.

**Comment by ericbsd** [comment]
> Also, did you see my feature request for adding NetBSD support to networkmgr? Do you think that networkmgr should work already under NetBSD if its files got installed in the right paths? That's the impression I have.

NetworkMgr will not work as it is on NetBSD. For GhostBSD supporting NetBSD is out of the scope of GhostBSD.

If someone wants to contribute to making it work under NetBSD, they are welcome to do that.
